### ISSUE TITLE
Missing CellProfiler Profiles

### ISSUE THREAD

**Issue by wongdanr** [jump-cellpainting/2021_Chandrasekaran_submitted#45]
Hello @niranjchandrasekaran,
I noticed that some of the CellProfiler profiles are missing. For instance, plate 2020_11_04_CPJUMP1/BR00116995 is missing profiles for A06, A13, C11, etc. It would be greatly beneficial if these can be provided. Thanks!

**Comment by niranjchandrasekaran** [comment]
Hi @wongdanr, this plate (BR00116995) had some issues and profiles were generated only for 301 wells. IIUC, there were  [many empty fields](https://github.com/jump-cellpainting/pilot-cpjump1-analysis/issues/13#issuecomment-799779409) (private repo) on this plate.

**Comment by wongdanr** [comment]
Oh I see interesting ok thanks, I will exclude them then. Thank you!
