### ISSUE TITLE
Preliminary mean average precision calculations

### ISSUE THREAD

**Issue by niranjchandrasekaran** [jump-cellpainting/2021_Chandrasekaran_submitted#51]
As we are beginning to move towards using `mean average precision (mAP)` in the place of `Percent scores` in all our projects, I calculated `mAP` for this dataset as well. The following are the `mAP` plots and tables, along with the same for `Percent Replicating` and `Percent Matching`, for reference.

#### mAP
[Notebook1](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/10.average_precision_replicating.ipynb), [Notebook2](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/12.average_precision_repliating_dl.ipynb) and [Notebook3](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/13.generate_figure_mAP.ipynb)

![13 figure](https://user-images.githubusercontent.com/19695854/168178687-6b74c376-f3a6-4775-9dcb-42871b497d16.png)

#### Percent Replicating

[Notebook1](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/1.percent_replicating.ipynb), [Notebook2](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/4.percent_replicating_dl.ipynb), [Notebook3](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/7.generate_figure.ipynb)

![7 figure](https://user-images.githubusercontent.com/19695854/168178650-71b190c8-6d79-4c27-b08b-dc5336b4b341.png)

#### mAP
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/58583b45e01e06da7a642dd92b7f955e2fe37226/benchmark/11.average_precision_matching.ipynb)

![11 mAP_heatmap](https://user-images.githubusercontent.com/19695854/168180529-96d4c508-db21-4413-9509-777013bbefaf.png)

![11 mAP_matching](https://user-images.githubusercontent.com/19695854/168179197-55f07298-e1c0-46ae-bbfa-53b60ce71d22.png)

#### Percent Matching
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/a18fd7719c05b638c731142b0d42a92c645e2b33/benchmark/9.account_for_compound_polypharmacology.ipynb)

![9 percent_matching_heatmap](https://user-images.githubusercontent.com/19695854/168179243-11e18278-b9af-482f-abdb-3bd4e16abeb7.png)

Since I don't have intuition for `mAP` values yet, I found the following results odd, and I wanted to know what you thought about them, @shntnu,
1. For the replicate retrieval task, `mAP` of the true replicates and shuffled replicates are similar for Cell Profiler features while for DeepProfiler features, even though `mAP` value is smaller, the difference between that of true and shuffled replicates is an order of magnitude larger.
2. For the gene-compound match retrieval task, `mAP` values look very similar for all CRISPR vs. compound conditions and for all ORF vs. compound conditions.

I wanted to get your thoughts before I dive deeper into the code and make sure there are no bugs (so far I haven't found any).

**Comment by niranjchandrasekaran** [comment]
@shntnu Ignore this issue for the time being. I will ping you later once it is ready. I think I have found a couple of things that could be wrong.

**Comment by shntnu** [comment]
Sounds good @niranjchandrasekaran

**Comment by niranjchandrasekaran** [comment]
I found that I was not removing self correlations from the `AP` calculations. Setting self correlations to `0` and changing the `truth matrix` value also `0` changed the results for the replicate retrieval task.

### Replicate retrieval task
[Notebook1](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/9632fd3401d0c9c871c5ff1e942bb5a1dfb64e87/benchmark/10.average_precision_replicating.ipynb), [Notebook2](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/9632fd3401d0c9c871c5ff1e942bb5a1dfb64e87/benchmark/12.average_precision_repliating_dl.ipynb), [Notebook3](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/9632fd3401d0c9c871c5ff1e942bb5a1dfb64e87/benchmark/13.generate_figure_mAP.ipynb)

![13 figure](https://user-images.githubusercontent.com/19695854/168929161-e8363982-8274-419b-b6a2-f87a9d838de5.png)

DeepProfiler now seems to perform better than CellProfiler and the null for the CellProfiler features now looks similar to that of DeepProfiler features (in fact even smaller).

**Comment by niranjchandrasekaran** [comment]
At this point, I spoke to Shantanu, who suggested that I check a couple of things before we begin interpreting the results/looking of bugs.

1. Plot the per sample average precision values
2. Replace the correlation matrix with a ranked list of correlations. If the average precision calculation is correct, then there should be no change in the results.

**Comment by niranjchandrasekaran** [comment]
Here are the results from the two debugging exercises.

### Plotting per sample average precision values
#### All samples
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/05be9f9a5b831331b841b27eef435492d322b897/benchmark/10.average_precision_replicating.ipynb)

I first plotted this for all samples. For compounds, the distribution shifts towards the right. This explains the high scores. It is not clear if that for that many samples, the average precision should be close to 1.
![10 compound_ap](https://user-images.githubusercontent.com/19695854/168929743-bbda1d16-dab6-447a-8a24-49cc1bb32e98.png)

![10 crispr_ap](https://user-images.githubusercontent.com/19695854/168929817-9d796c78-9435-4b0d-81bc-b2411ce8774a.png)

![10 compound_ap](https://user-images.githubusercontent.com/19695854/168929825-a8e77643-4f94-4f21-84ff-aa20e38acb02.png)

#### Only poscons
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/05be9f9a5b831331b841b27eef435492d322b897/benchmark/14.average_precision_replicating_poscon.ipynb)

As a sanity check, I repeated the analysis with only the poscons. Since some poscons (`poscon_diverse`) are diverse in nature and also have a strong signature, I expected the mean average precision to increase, which is what I see below. The same is seen for the genetic perturbation experiments as well.

![14 mAP_CellProfiler_poscons](https://user-images.githubusercontent.com/19695854/168930137-b6c104fa-8b1b-41ec-
b2a9-108b6f0b44cf.png)

![14 compound_ap_poscon](https://user-images.githubusercontent.com/19695854/168930154-f504f65a-9b73-4646-be19-498fb18fbbdc.png)

![14 crispr_ap_poscon](https://user-images.githubusercontent.com/19695854/168930164-79cac8b8-06ad-4050-9f5c-
f929074dc032.png)

![14 orf_ap_poscon](https://user-images.githubusercontent.com/19695854/168930180-f1855edd-84db-45af-a978-acf691369397.png)

### Replace the correlation matrix with the ranked list of correlations

[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/05be9f9a5b831331b841b27eef435492d322b897/benchmark/15.average_precision_replicating_rank_poscon.ipynb)

I converted the correlation matrix to a ranked list and computed `mAP` for the poscons. The results are [identical to when I used the correlation matrix](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/05be9f9a5b831331b841b27eef435492d322b897/benchmark/14.average_precision_replicating_poscon.ipynb).

cc @shntnu

**Comment by niranjchandrasekaran** [comment]
At our meeting on 2022-05-19, Shantanu suggested that I compute both mean precision@k and mean precision@r in addition to mean average precision to determine which metric will be best suited for replacing `percent replicating` and `percent matching`. Additionally, I also began computing the precision metrics using the absolute correlation values for matching between compounds and genes because compound-gene matches could be correlated or ant-correlated. We also decided to call the signal and null values `Real` and `Permuted` to be consistent with the nomenclature used in the cell health paper. I set `k=5` for precision@k calculation, which I chose arbitrarily. Anne said that the heatmaps for matching were confusing to look at, and hence I replaced them with bar plots.

### Main takeaways
- There is a strong correlation between mean average precision (mAP) and mean precision@r (mPr), which we expected.

### Replicate retrieval
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/06e9f613c34b7ee0380a4841c66a100c1225c7fa/benchmark/10.average_precision_replicating.ipynb)

![10 mAP_CellProfiler](https://user-images.githubusercontent.com/19695854/171628410-7a7d1e53-2f6b-41da-a654-ccf49e0c6f67.png)

![10 mPk_CellProfiler](https://user-images.githubusercontent.com/19695854/171628693-16f09bb7-6fc9-4111-b85f-cd67741fe7ee.png)

![10 mPr_CellProfiler](https://user-images.githubusercontent.com/19695854/171628723-489bb19d-7a84-4a2f-ab0d-1d6ad9964e82.png)

### Gene-compound match retrieval
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/06e9f613c34b7ee0380a4841c66a100c1225c7fa/benchmark/11.average_precision_matching.ipynb)

![11 mAP_matching](https://user-images.githubusercontent.com/19695854/171629020-ab74fe54-5263-4611-82f9-90a04634a9ae.png)

![11 mPk_matching](https://user-images.githubusercontent.com/19695854/171628998-941723a0-553b-44b5-b3b1-fe0266c617fe.png)

![11 mPr_matching](https://user-images.githubusercontent.com/19695854/171629053-7fbcb0cc-3840-4749-8bb4-22d1b80eed91.png)

**Comment by niranjchandrasekaran** [comment]
At our meeting on 2022-05-25, Shantanu said that for interpretability, we will stick with mAP and mP@r and drop mP@k. 

Additionally, Shantanu suggested the following,
- For generating the null, I was shuffling both sample labels and features. Shantanu said that this maybe too conservative and asked me not to shuffle the features. So, I have changed the shuffling approach. 
- For making the precision values interpretable, like our `percent scores`, compute the proportion of perturbations whose P@r is greater than a range of thresholds. The hope is to plot this and then decide on a special threshold value that give us a single metric, which is also interpretable.
- challenge vs. negcon – currently, the precision values are computed by assuming that we can separate the replicates of query compound from replicates of other compounds. But we could also pose the problem differently to see if we can separate the replicates of the query compound from DMSO. Shantanu said that this might work better, especially in the case where we trust our negative controls. I am not sure what happens in the case of CRISPR and ORF, where we don't trust the negative controls.

## Main takeaways
- Challenging vs. negcon increases the precision values for both `Real` and `Permuted` cases.
   - The amount the precision values change may have something to do with the quality of negcons. 

## Results
### Replicate retrieval
#### Challenge vs. other compounds
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/3bdea4106886e3cc465b17f7894dac4fcd24cae0/benchmark/10.average_precision_replicating.ipynb)
![10 mAP_CellProfiler](https://user-images.githubusercontent.com/19695854/171635662-1cea050e-bfa8-4c57-bfab-ffaef6398ec6.png)

![10 mPr_CellProfiler](https://user-images.githubusercontent.com/19695854/171635697-4a4bc878-d984-465b-b4eb-fdc20f35d616.png)

![10 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/171635731-d74d65c4-ce41-4b0b-a4f1-2cab46a71584.png)

#### Challenge vs. negcon
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/3bdea4106886e3cc465b17f7894dac4fcd24cae0/benchmark/16.average_precision_replicating_negcon.ipynb)

![16 mAP_CellProfiler](https://user-images.githubusercontent.com/19695854/171635768-1f7d3574-5fef-48ca-a43c-1c709c852dcd.png)

![16 mPr_CellProfiler](https://user-images.githubusercontent.com/19695854/171635782-4d012f4d-469f-4d50-8876-c911cbde49b9.png)

![16 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/171635792-7b10e54c-9985-4039-89da-0337feffe27f.png)

### Gene-compound match retrieval
#### Challenge vs. other compounds
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/3bdea4106886e3cc465b17f7894dac4fcd24cae0/benchmark/11.average_precision_matching.ipynb)

![11 mAP_matching](https://user-images.githubusercontent.com/19695854/171636002-392e6f3b-e119-49a6-885b-020cef929fa7.png)

![11 mAPr_matching](https://user-images.githubusercontent.com/19695854/171636049-1f75551a-6255-43cf-93b7-2e5826c08e2c.png)

![11 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/171636062-9bac2c9b-0640-4528-8250-c13147f6d9e7.png)

#### Challenge vs. negcon
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/3bdea4106886e3cc465b17f7894dac4fcd24cae0/benchmark/17.average_precision_matching_negcon.ipynb)

![17 mAP_matching](https://user-images.githubusercontent.com/19695854/171636098-f750bb4e-b3ee-46a0-9d8a-9828649a9b8d.png)

![17 mPr_matching](https://user-images.githubusercontent.com/19695854/171636115-18f4cdfc-ed57-442d-a218-6d963b564c05.png)

![17 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/171636145-8e08ed5f-d8d6-4818-9fc0-9773a244a204.png)

**Comment by niranjchandrasekaran** [comment]
The results of the gene-compound match retrieval task have always looked suspicious because of how similar the values looked across all cell types and time points. I identified a bug in the code and after fixing it, the results look as follows

 ### Gene-compound match retrieval
#### Challenge vs. other compounds
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/5d4317b94f4e5b800d5fbb39e0a026ab5a56cdda/benchmark/11.average_precision_matching.ipynb)

![11 mAP_matching](https://user-images.githubusercontent.com/19695854/172495524-93826ea4-f8f2-4033-8172-f39e90be0784.png)

![11 mPr_matching](https://user-images.githubusercontent.com/19695854/172495532-565941d2-2918-4032-aa9e-44fe2a32920f.png)

![11 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/172495543-262004bc-4720-4176-aede-9c9b5c5736a8.png)

#### Challenge vs. negcon
[Notebook](https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/blob/5d4317b94f4e5b800d5fbb39e0a026ab5a56cdda/benchmark/17.average_precision_matching_negcon.ipynb)

![17 mAP_matching](https://user-images.githubusercontent.com/19695854/172495587-ca46a4c5-71a6-4b46-a634-241b7a5f851a.png)

![17 mPr_matching](https://user-images.githubusercontent.com/19695854/172495599-7e5f6920-7902-47ab-8604-5cef771e4c29.png)

![17 percent_perturbation_curves](https://user-images.githubusercontent.com/19695854/172495605-2a8d33fc-c12c-412a-93cb-8c75e039c5f2.png)

These results are more believable.
