### ISSUE TITLE
Unable to download batch of data from s3

### ISSUE THREAD

**Issue by NiketPatel9** [jump-cellpainting/2021_Chandrasekaran_submitted#7]
Hello,

I am trying to download the dataset that is represented on your repository. The images and accompanying metadata will be very useful for a project I am currently working on. I am currently attempting the file transfer from the S3 bucket specified on your README to an EC2 instance. Currently, I am only attempting to download a single batch of data, 2020_11_19_TimepointDay4, just to validate that it can be done.
 
I am running the following command: 
`aws s3 cp --request-payer requester --recursive s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/ .` to download it to the current directory in my EC2 instance, but I am getting the following error: 
`download failed: s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/images/<file_path> to images/<file_path> An error occurred (AccessDenied) when calling the GetObject operation: Access Denied`
This occurs for every file in the batch. Even though the images are not downloaded, the corresponding directories are created with their structure intact. However, they are not populated with images.

I also attempted a direct s3 to s3 transfer, with no luck and a similar error:
`aws s3 cp --request-payer requester --recursive s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/ s3://ucbelement-jump-cellpainting/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/
`
getting the following error:
`copy failed: s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/images/<file_path> to s3://ucbelement-jump-cellpainting/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/images/<file_path> An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
`

Any suggestions on how to get this file transfer working or perhaps an alternate approach to access these images would be greatly appreciated.

Thank you.

**Comment by niranjchandrasekaran** [comment]
Hi @NiketPatel9 Thank you for your interest in our dataset. I am tagging @shntnu who should be able to help you with this.

**Comment by shntnu** [comment]
Can you try again but using the `--no-sign-request` flag?

**Comment by NiketPatel9** [comment]
@shntnu 
I tried the following command: `aws s3 cp --request-payer requester --recursive s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/ . --no-sign-request` and variations, and they all lead to the following error:
`fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`. I am unsure as to what is causing these permission issues. Do you recommend another method of retrieving this dataset?

**Comment by shntnu** [comment]
Oops, please try the original command again. The permissions were set incorrectly,

```sh
aws s3 cp --request-payer requester --recursive s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_19_TimepointDay4/ .
```

LMK if that doesn't work

**Please note** `--request-payer requester ` means that your AWS account will be [charged for access](https://aws.amazon.com/s3/pricing/).

**Comment by NiketPatel9** [comment]
@shntnu 
Thank you! That seems to work. I am able to see the files now.

**Comment by shntnu** [comment]
Awesome!

**Comment by NiketPatel9** [comment]
@shntnu 
One last thing, could you be a bit more specific in terms of costs of file transfer? I am in the US-east-1 region.

**Comment by shntnu** [comment]
Have a look at the data transfer tab on this page
https://aws.amazon.com/s3/pricing/ to get per GB cost

To know the size of a specific folder, you can use the summarize option of
ls
https://docs.aws.amazon.com/cli/latest/reference/s3/ls.html
