### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by ethancohen123** [jump-cellpainting/2021_Chandrasekaran_submitted#71]
Hi,
I wonder if there is a way to download the deep profiles/cell profiler profiles without doing the whole pipeline ? If yes, are there already aggregated per well or is it possible to get the raw profiles ?
Im sorry if the information are already present and therefore missed it.
Thanks

**Comment by niranjchandrasekaran** [comment]
Hi @ethancohen123, 

You can clone this repo, and you will find the well-level aggregated profiles (both CellProfiler features and DeepProfiler features) in the folders `profiles`. You don't have to re-run the pipeline. The single cell profiles for DeepProfiler features are not available, but the single-cell profiles for CellProfiler can be downloaded as `.sqlite` files from `s3://cellpainting-gallery/cpg0000-jump-pilot/source_4/workspace/backend/`.

**Comment by ethancohen123** [comment]
Oh I see thanks.
How to differentiate the one with Cell Profiler and the one with Deep profiler in Profiles/ ?

**Comment by niranjchandrasekaran** [comment]
We don't have DeepProfiler features for all the plates. We have profiles only for 10 plates. You can find them in https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/tree/main/profiles/2020_11_04_CPJUMP1_DL. The remaining profiles in https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted/tree/main/profiles/ are CellProfiler features.
