### ISSUE TITLE
Evaluating style transfer on extracted profiles

### ISSUE THREAD

**Issue by shntnu** [jump-cellpainting/2021_Chandrasekaran_submitted#9]
Let's evaluate how well we can translate profiles across experimental conditions.

We could pick several different pairs of conditions in this dataset, but we're considering focussing on cell type translation because that's the most compelling example.

@niranjchandrasekaran can you list what we have here?

U2OS and A549, across two timepoints, for JUMP-Target and JUMP-MOA plates, right? 

cc @AnneCarpenter

**Comment by AnneCarpenter** [comment]
Doesn't CPJUMP1 only have JUMP-Target1 compound plates? 
We could transfer styles across cell types for one timepoint (using the other timepoint as heldout case)
AND across timepoints for one cell type (using timepoints in the other cell type as heldout case) 
(or just one of those)

**Comment by niranjchandrasekaran** [comment]
> U2OS and A549, across two timepoints, for JUMP-Target and JUMP-MOA plates, right?

We only have JUMP-Target

> can you list what we have here?

We have different cell types (U2OS and A549), time points (low and high), perturbation modality (ORF, CRISPR, Compound), densities (-20%, baseline, 20%), cell line (Parental and monoclonal) and selection (presence and absence of Puromycin and Blasticidin).

**Comment by shntnu** [comment]
Thanks for clarifying.

I've temporarily moved this to a gdoc thread where we discussed this idea previously https://docs.google.com/document/d/1k7ChkKX8DTzP2_eV4UqDP_ZywRpDnciS9TD1S-fYQjU/edit?disco=AAAALGYZ_Bs

**Comment by shntnu** [comment]
We're good to proceed with the plan of doing this

It's best to minimize the number of sources of technical variation, so let's simplify:

Strawman plan:
We will use
- 4 replicates A549 JUMP-Target-Compound Plate at 48h
- 4 replicates U2OS JUMP-Target-Compound Plate at 48h
- Split the 306 compounds into 80/20 train/test
- Train/validate a model to predict U2OS signature given A549 signature on the 80%, test on the 20%. We will report  precision@K on the test dataset i.e. how well can I retrieve the real U2OS replicates for a compound, given the translated (i.e. synthetic) U2OS profile? We can't report percent matching because 20% is too little. We can report percent replicating I suppose.

**Comment by shntnu** [comment]
@MarziehHaghighi feel free to ask for what you need in this thread

**Comment by AnneCarpenter** [comment]
We are concerned there is not sufficient time to carry out an experiment like this before the paper deadline, unfortunately. Marzieh is going to think about it.

**Comment by MarziehHaghighi** [comment]
@AnneCarpenter @shntnu 
Note that in our work "style" is "treatment" and another cell-type would be another unseen cell identity. Using that model for this much simpler problem is a huge overkill and is not justifiable. Here, "style" is cell type and we have two style and many example to learn that binary styles independent of treatment etc. I try to see if I can run a NST quick model on the data here. 
@niranjchandrasekaran Could you please share the location of images/metadata with me?

**Comment by AnneCarpenter** [comment]
Logistically, it's great to use a simpler method because (a) you are more
likely to be able to finish in time, and (b) it won't interfere w your
style transfer paper in progress!

**Comment by niranjchandrasekaran** [comment]
> Could you please share the location of images/metadata with me?

Images are here - s3://jump-cellpainting-public/projects/2019_07_11_JUMP-CP-pilots/2020_11_04_CPJUMP1/

Based on what Shantanu said in https://github.com/jump-cellpainting/neurips-cpjump1/issues/9#issuecomment-901323453, the plates that will be useful to you are

Plate name | Description
-- | --
BR00117017 | A549 48-hour Compound Plate 1
BR00117019 | A549 48-hour Compound Plate 2
BR00117015 | A549 48-hour Compound Plate 3
BR00117016 | A549 48-hour Compound Plate 4
BR00117012 | U2OS 48-hour Compound Plate 1
BR00117013 | U2OS 48-hour Compound Plate 2
BR00117010 | U2OS 48-hour Compound Plate 3
BR00117011 | U2OS 48-hour Compound Plate 4

Here is the plate map - https://github.com/jump-cellpainting/neurips-cpjump1/blob/main/metadata/platemaps/2020_11_04_CPJUMP1/platemap/JUMP-Target-1_compound_platemap.txt

and here is additional metadata - 
https://github.com/jump-cellpainting/neurips-cpjump1/blob/main/metadata/moa/JUMP-Target-1_compound_metadata.tsv

(you can combine the plate map and additional metadata using `broad_sample`.

Let me know if you need anything else.
